
site_name: 私の研究ドキュメント

theme:
  name: material
  features:
    - content.code.copy
    - navigation.tabs
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/weather-night
        name: ダークモードへ
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/weather-sunny
        name: ライトモードへ
    

plugins:
  search:
    lang: ja

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      use_pygments: true
      noclasses: false
      pygments_style: monokai
      linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js

extra_css:
    - extra.css

nav:
    - トップページ: index.md
    - ノート: notes.md
    - プログラミング:
      - MkDocs:
          - はじめに: programming/mkdocs/intro.md
          - 基本運用: programming/mkdocs/basics.md
          - 使い方: programming/mkdocs/usage.md
          - Tips集: programming/mkdocs/tips.md
      - Remote SSH:
          - はじめに: programming/remoteSSH/intro.md
          - 接続設定: programming/remoteSSH/setup.md
          - 使い方: programming/remoteSSH/usage.md
          - Tips集: programming/remoteSSH/tips.md
      - Git / GitHub:
          - はじめに: programming/git/intro.md
          - 基本操作: programming/git/basics.md
          - リモートとGitHub: programming/git/github.md
          - ブランチと運用: programming/git/branching.md
          - トラブル対応: programming/git/troubleshooting.md
          - 家／研究室ワークフロー: programming/git/workflow.md
      - Python:
          - はじめに: programming/python/intro.md
          - 基本運用: programming/python/basics.md
          - 使い方: programming/python/usage.md
          - Tips集: programming/python/tips.md
      - VS Code:
          - はじめに: programming/vscode/intro.md
          - 使い方: programming/vscode/usage.md
          - Tips集: programming/vscode/tips.md

    - 授業ノート:
      - 非線形物理:
          - 第1回: Classes/non-linear-phys/lec01.md
          - 第2回: Classes/non-linear-phys/lec02.md
      - グリーン関数（水野）:
          - Part 1: Classes/Green_function_mizuno/part1.md
          - Part 2: Classes/Green_function_mizuno/part2.md
          - Part 3: Classes/Green_function_mizuno/part3.md
          - newpart3: Classes/Green_function_mizuno/newpart3.md
      - Reading circle M1:
          - まとめ1: Classes/Reading_circle_M1/summary1.md
          - まとめ2: Classes/Reading_circle_M1/summary2.md
          - まとめ3: Classes/Reading_circle_M1/summary3.md
          - まとめ4: Classes/Reading_circle_M1/summary4.md
          - まとめ5: Classes/Reading_circle_M1/summary5.md

    - LAB:
      - ミーティング資料:
          - 2025-10-24 栫: LAB/meeting/2025_10_24_kakoi.md

    - 量子多体系のための摂動論:
      - 概要: perturbation/abst.md
      - グリーン関数: 
          - グリーン関数と諸性質: perturbation/green/green.md
          - 温度グリーン関数と諸性質: perturbation/green/tempgreen.md
          - 遅延・先進グリーン関数: perturbation/green/RAgreen.md

      - 相互作用とファインマンダイアグラム:
          - 相互作用のグリーン関数: perturbation/fd/interaction.md
          - ブロッホドミニシスの定理: perturbation/fd/bloch.md
          - ファインマンダイアグラム: perturbation/fd/fd.md
          - 自己エネルギーとダイソン方程式: perturbation/fd/dyson.md
          - 相互作用のFD: perturbation/fd/fd_interaction.md

      - 線形応答理論:
          - 応答関数の諸性質: perturbation/lrt/rf.md
          - 電荷感受率: perturbation/lrt/charge.md
          - 磁気感受率: perturbation/lrt/spin.md
          - RPA近似: perturbation/lrt/others.md

      - RPA(計算): 
          - 概要: perturbation/rpa/abst.md
          - RPAの基礎: perturbation/rpa/rpa.md
          - コード解説1 感受率: perturbation/rpa/susceptibility.md
          - スピン感受率メモ: perturbation/rpa/spin_susceptibility.md
          - コード解説2 相互作用の導入: perturbation/rpa/interaction.md
          - コード解説3 自己エネルギー: perturbation/rpa/self-energy.md
          - コード解説4 グリーン関数: perturbation/rpa/green_function.md

    - 基礎固体物理:
      - 概要: Solid_State_Phys/overview.md
      - 1. 基礎:
          - 結晶構造と格子ベクトル: Solid_State_Phys/basics/crystal_lattice.md
          - 逆格子とブリルアンゾーン: Solid_State_Phys/basics/reciprocal_lattice.md
          - ブロッホの定理と波動関数: Solid_State_Phys/basics/bloch_theorem.md
          - バンド構造と有効質量: Solid_State_Phys/basics/band_and_mass.md
          - フェルミ面と電子密度: Solid_State_Phys/basics/fermi_surface.md

      - 2. 模型:
          - 模型全体の俯瞰: Solid_State_Phys/models/overview.md
          - 自由電子模型: Solid_State_Phys/models/free_electron/overview.md
          - NFE近似: Solid_State_Phys/models/nearly_free_electron/overview.md
          - 強束縛模型 (Tight Binding):
              - 概要: Solid_State_Phys/models/tight_binding/overview.md
              - 原子軌道からの導出: Solid_State_Phys/models/tight_binding/derivation.md
              - 分散関係の例: Solid_State_Phys/models/tight_binding/dispersion.md
              - 局在性とバンド幅: Solid_State_Phys/models/tight_binding/localization.md
          - ハバード模型: Solid_State_Phys/models/hubbard/overview.md
          - 模型の比較と限界: Solid_State_Phys/models/comparison.md

      - 3. 熱・フォノン:
          - 格子振動とフォノン: Solid_State_Phys/phonon/overview.md
          - デバイ模型と比熱: Solid_State_Phys/phonon/debye.md
          - フォノン分散と音速: Solid_State_Phys/phonon/dispersion.md
          - 熱伝導とフォノン散乱: Solid_State_Phys/phonon/thermal_conductivity.md
          - 電子−格子相互作用: Solid_State_Phys/phonon/electron_phonon.md

      - 4. 電気特性:
          - ドリューデ模型とフェルミ液体: Solid_State_Phys/transport/drude.md
          - 半導体の電子・正孔伝導: Solid_State_Phys/transport/semiconductor.md
          - ホール効果・磁気抵抗: Solid_State_Phys/transport/hall_effect.md
          - 光応答・誘電関数: Solid_State_Phys/transport/optical_response.md
          - 熱電効果とSeebeck係数: Solid_State_Phys/transport/thermoelectric.md

      - 5. 磁性:
          - スピンと磁気モーメント: Solid_State_Phys/magnetism/spin.md
          - 常磁性・反磁性・強磁性: Solid_State_Phys/magnetism/types.md
          - ハイゼンベルグ模型（統計へ橋渡し）: Solid_State_Phys/magnetism/heisenberg.md
          - スピン波と量子磁性: Solid_State_Phys/magnetism/spinwave.md
          - 統計的取り扱いと相転移: Solid_State_Phys/magnetism/statistical_link.md

    - Research:
      - 概要: research/overview.md
      - 2D 正方格子:
          - バンド分散: research/square/band.md
          - 多軌道に拡張する: research/square/multiband.md
          - 状態密度 (DOS): research/square/dos.md
          - 充填率と化学ポテンシャル: research/square/filling_mu.md
          - グリーン関数: research/square/green.md
          - 感受率とRPA: research/square/rpa.md
          - FLEX計算: research/square/flex.md

      - 2D ハニカム格子:
          - バンド分散: research/honeycomb/band.md
          - DOSとフェルミ準位: research/honeycomb/dos.md
          - RPA計算結果: research/honeycomb/rpa.md
          - FLEX解析: research/honeycomb/flex.md

      - DFTとWannier化:
          - DFT理論と実装: research/dft/overview.md
          - 実例_VASPからWannier90ワークフロー: research/dft/workflow.md
          - wannier_hr.datからの再構築: research/dft/wannier_rebuild.md          





      

